version: "3"
services:
 xxl-job-admin:
    image: registry.cn-beijing.aliyuncs.com/wavewisdom-bj-registry-develop/github-xxl-job:2.0.0
    container_name: xxl-job-admin
    environment:
      - PARAMS=--spring.profiles.active=dev
    volumes:
    - /etc/hosts:/etc/hosts
    - /etc/localtime:/etc/localtime:ro
    restart: always